name: Build Debian package on ubuntu 20.04
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Update image
        run: apt update
      - name: Install make
        run: apt install -y build-essential
      - name: Install dependencies
        run: make requirements

      - name: Build package
        run: make package

      - name: Upload debian package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: safeboot-unstable.deb
