name: Build debain package
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo make requirements

      - name: Build package
        run: make package
