name: Build debain package
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Install make
        run: apt install build-essential
      - name: Install dependencies
        run: make requirements

      - name: Build package
        run: make package
